/******************************************************************************/
/* Change log                                                                 *
 *
 *
 *
 * Date         Revision    Comments
 * MM/DD/YY
 * --------     ---------   ----------------------------------------------------
 * 08/25/15     2.0_DW0a    Initial project make.
/******************************************************************************/

/******************************************************************************/
/* Files to Include                                                           */
/******************************************************************************/
#ifndef FLASH_H
#define	FLASH_H

#if defined(__XC)
    #include <xc.h>         /* XC8 General Include File */
#elif defined(HI_TECH_C)
    #include <htc.h>        /* HiTech General Include File */
#elif defined(__18CXX)
    #include <p18cxxx.h>    /* C18 General Include File */
#endif

#if defined(__XC) || defined(HI_TECH_C)
#include <stdint.h>        /* For uint8_t definition */
#include <stdbool.h>       /* For true/false definition */
#include <stdio.h>       /* For true/false definition */
#include <string.h>
#endif

/******************************************************************************/
/* WRITETRIES

 *
 * This is the number of tries that we will attempt to write to flash.
/******************************************************************************/
#define WRITETRIES   10

/******************************************************************************/
/* LARGEST_MEM_ADR

 *
 * This is the highest flash address. For PIC18FX4J10 this is 0x3600.
 * For PIC18FX5J10, this is 0x7600.
/******************************************************************************/
#define LARGEST_MEM_ADR   0x3600

/******************************************************************************/
/* WASTEFLAG

 *
 * This is the pattern to fill the wasted flash with.
/******************************************************************************/
#define WASTEFLAG   0xDA

/******************************************************************************/
/* EECON1

 *
 * This is the parameters of EECON1
/******************************************************************************/
#define b_WR      0b00000010
#define b_WREN    0b00000100
#define b_WRERR   0b00001000
#define b_FREE    0b00010000

/******************************************************************************/
/* Defines                                                                    */
/******************************************************************************/

/******************************************************************************/
/* Variable to make erased flash non-fillable. This is done because we do not
 *  have enough RAM to save the entire block, erase and rewrite.   
 * 
 * Calculation:
 *                
 * - Size:
 * 1024 - (IRBUFFERSIZE * 2 + RFBUFFERSIZE * 2) = 512;
 * 
 * - Place:
 * start address of IR_SavedTiming + 512 = 0x2600;      
/******************************************************************************/
const unsigned char FlashWaste[512] __at(0x2600) = {
                                            WASTEFLAG,    //    [    0    ]
                                            WASTEFLAG,    //    [    1    ]
                                            WASTEFLAG,    //    [    2    ]
                                            WASTEFLAG,    //    [    3    ]
                                            WASTEFLAG,    //    [    4    ]
                                            WASTEFLAG,    //    [    5    ]
                                            WASTEFLAG,    //    [    6    ]
                                            WASTEFLAG,    //    [    7    ]
                                            WASTEFLAG,    //    [    8    ]
                                            WASTEFLAG,    //    [    9    ]
                                            WASTEFLAG,    //    [    10    ]
                                            WASTEFLAG,    //    [    11    ]
                                            WASTEFLAG,    //    [    12    ]
                                            WASTEFLAG,    //    [    13    ]
                                            WASTEFLAG,    //    [    14    ]
                                            WASTEFLAG,    //    [    15    ]
                                            WASTEFLAG,    //    [    16    ]
                                            WASTEFLAG,    //    [    17    ]
                                            WASTEFLAG,    //    [    18    ]
                                            WASTEFLAG,    //    [    19    ]
                                            WASTEFLAG,    //    [    20    ]
                                            WASTEFLAG,    //    [    21    ]
                                            WASTEFLAG,    //    [    22    ]
                                            WASTEFLAG,    //    [    23    ]
                                            WASTEFLAG,    //    [    24    ]
                                            WASTEFLAG,    //    [    25    ]
                                            WASTEFLAG,    //    [    26    ]
                                            WASTEFLAG,    //    [    27    ]
                                            WASTEFLAG,    //    [    28    ]
                                            WASTEFLAG,    //    [    29    ]
                                            WASTEFLAG,    //    [    30    ]
                                            WASTEFLAG,    //    [    31    ]
                                            WASTEFLAG,    //    [    32    ]
                                            WASTEFLAG,    //    [    33    ]
                                            WASTEFLAG,    //    [    34    ]
                                            WASTEFLAG,    //    [    35    ]
                                            WASTEFLAG,    //    [    36    ]
                                            WASTEFLAG,    //    [    37    ]
                                            WASTEFLAG,    //    [    38    ]
                                            WASTEFLAG,    //    [    39    ]
                                            WASTEFLAG,    //    [    40    ]
                                            WASTEFLAG,    //    [    41    ]
                                            WASTEFLAG,    //    [    42    ]
                                            WASTEFLAG,    //    [    43    ]
                                            WASTEFLAG,    //    [    44    ]
                                            WASTEFLAG,    //    [    45    ]
                                            WASTEFLAG,    //    [    46    ]
                                            WASTEFLAG,    //    [    47    ]
                                            WASTEFLAG,    //    [    48    ]
                                            WASTEFLAG,    //    [    49    ]
                                            WASTEFLAG,    //    [    50    ]
                                            WASTEFLAG,    //    [    51    ]
                                            WASTEFLAG,    //    [    52    ]
                                            WASTEFLAG,    //    [    53    ]
                                            WASTEFLAG,    //    [    54    ]
                                            WASTEFLAG,    //    [    55    ]
                                            WASTEFLAG,    //    [    56    ]
                                            WASTEFLAG,    //    [    57    ]
                                            WASTEFLAG,    //    [    58    ]
                                            WASTEFLAG,    //    [    59    ]
                                            WASTEFLAG,    //    [    60    ]
                                            WASTEFLAG,    //    [    61    ]
                                            WASTEFLAG,    //    [    62    ]
                                            WASTEFLAG,    //    [    63    ]
                                            WASTEFLAG,    //    [    64    ]
                                            WASTEFLAG,    //    [    65    ]
                                            WASTEFLAG,    //    [    66    ]
                                            WASTEFLAG,    //    [    67    ]
                                            WASTEFLAG,    //    [    68    ]
                                            WASTEFLAG,    //    [    69    ]
                                            WASTEFLAG,    //    [    70    ]
                                            WASTEFLAG,    //    [    71    ]
                                            WASTEFLAG,    //    [    72    ]
                                            WASTEFLAG,    //    [    73    ]
                                            WASTEFLAG,    //    [    74    ]
                                            WASTEFLAG,    //    [    75    ]
                                            WASTEFLAG,    //    [    76    ]
                                            WASTEFLAG,    //    [    77    ]
                                            WASTEFLAG,    //    [    78    ]
                                            WASTEFLAG,    //    [    79    ]
                                            WASTEFLAG,    //    [    80    ]
                                            WASTEFLAG,    //    [    81    ]
                                            WASTEFLAG,    //    [    82    ]
                                            WASTEFLAG,    //    [    83    ]
                                            WASTEFLAG,    //    [    84    ]
                                            WASTEFLAG,    //    [    85    ]
                                            WASTEFLAG,    //    [    86    ]
                                            WASTEFLAG,    //    [    87    ]
                                            WASTEFLAG,    //    [    88    ]
                                            WASTEFLAG,    //    [    89    ]
                                            WASTEFLAG,    //    [    90    ]
                                            WASTEFLAG,    //    [    91    ]
                                            WASTEFLAG,    //    [    92    ]
                                            WASTEFLAG,    //    [    93    ]
                                            WASTEFLAG,    //    [    94    ]
                                            WASTEFLAG,    //    [    95    ]
                                            WASTEFLAG,    //    [    96    ]
                                            WASTEFLAG,    //    [    97    ]
                                            WASTEFLAG,    //    [    98    ]
                                            WASTEFLAG,    //    [    99    ]
                                            WASTEFLAG,    //    [    100    ]
                                            WASTEFLAG,    //    [    101    ]
                                            WASTEFLAG,    //    [    102    ]
                                            WASTEFLAG,    //    [    103    ]
                                            WASTEFLAG,    //    [    104    ]
                                            WASTEFLAG,    //    [    105    ]
                                            WASTEFLAG,    //    [    106    ]
                                            WASTEFLAG,    //    [    107    ]
                                            WASTEFLAG,    //    [    108    ]
                                            WASTEFLAG,    //    [    109    ]
                                            WASTEFLAG,    //    [    110    ]
                                            WASTEFLAG,    //    [    111    ]
                                            WASTEFLAG,    //    [    112    ]
                                            WASTEFLAG,    //    [    113    ]
                                            WASTEFLAG,    //    [    114    ]
                                            WASTEFLAG,    //    [    115    ]
                                            WASTEFLAG,    //    [    116    ]
                                            WASTEFLAG,    //    [    117    ]
                                            WASTEFLAG,    //    [    118    ]
                                            WASTEFLAG,    //    [    119    ]
                                            WASTEFLAG,    //    [    120    ]
                                            WASTEFLAG,    //    [    121    ]
                                            WASTEFLAG,    //    [    122    ]
                                            WASTEFLAG,    //    [    123    ]
                                            WASTEFLAG,    //    [    124    ]
                                            WASTEFLAG,    //    [    125    ]
                                            WASTEFLAG,    //    [    126    ]
                                            WASTEFLAG,    //    [    127    ]
                                            WASTEFLAG,    //    [    128    ]
                                            WASTEFLAG,    //    [    129    ]
                                            WASTEFLAG,    //    [    130    ]
                                            WASTEFLAG,    //    [    131    ]
                                            WASTEFLAG,    //    [    132    ]
                                            WASTEFLAG,    //    [    133    ]
                                            WASTEFLAG,    //    [    134    ]
                                            WASTEFLAG,    //    [    135    ]
                                            WASTEFLAG,    //    [    136    ]
                                            WASTEFLAG,    //    [    137    ]
                                            WASTEFLAG,    //    [    138    ]
                                            WASTEFLAG,    //    [    139    ]
                                            WASTEFLAG,    //    [    140    ]
                                            WASTEFLAG,    //    [    141    ]
                                            WASTEFLAG,    //    [    142    ]
                                            WASTEFLAG,    //    [    143    ]
                                            WASTEFLAG,    //    [    144    ]
                                            WASTEFLAG,    //    [    145    ]
                                            WASTEFLAG,    //    [    146    ]
                                            WASTEFLAG,    //    [    147    ]
                                            WASTEFLAG,    //    [    148    ]
                                            WASTEFLAG,    //    [    149    ]
                                            WASTEFLAG,    //    [    150    ]
                                            WASTEFLAG,    //    [    151    ]
                                            WASTEFLAG,    //    [    152    ]
                                            WASTEFLAG,    //    [    153    ]
                                            WASTEFLAG,    //    [    154    ]
                                            WASTEFLAG,    //    [    155    ]
                                            WASTEFLAG,    //    [    156    ]
                                            WASTEFLAG,    //    [    157    ]
                                            WASTEFLAG,    //    [    158    ]
                                            WASTEFLAG,    //    [    159    ]
                                            WASTEFLAG,    //    [    160    ]
                                            WASTEFLAG,    //    [    161    ]
                                            WASTEFLAG,    //    [    162    ]
                                            WASTEFLAG,    //    [    163    ]
                                            WASTEFLAG,    //    [    164    ]
                                            WASTEFLAG,    //    [    165    ]
                                            WASTEFLAG,    //    [    166    ]
                                            WASTEFLAG,    //    [    167    ]
                                            WASTEFLAG,    //    [    168    ]
                                            WASTEFLAG,    //    [    169    ]
                                            WASTEFLAG,    //    [    170    ]
                                            WASTEFLAG,    //    [    171    ]
                                            WASTEFLAG,    //    [    172    ]
                                            WASTEFLAG,    //    [    173    ]
                                            WASTEFLAG,    //    [    174    ]
                                            WASTEFLAG,    //    [    175    ]
                                            WASTEFLAG,    //    [    176    ]
                                            WASTEFLAG,    //    [    177    ]
                                            WASTEFLAG,    //    [    178    ]
                                            WASTEFLAG,    //    [    179    ]
                                            WASTEFLAG,    //    [    180    ]
                                            WASTEFLAG,    //    [    181    ]
                                            WASTEFLAG,    //    [    182    ]
                                            WASTEFLAG,    //    [    183    ]
                                            WASTEFLAG,    //    [    184    ]
                                            WASTEFLAG,    //    [    185    ]
                                            WASTEFLAG,    //    [    186    ]
                                            WASTEFLAG,    //    [    187    ]
                                            WASTEFLAG,    //    [    188    ]
                                            WASTEFLAG,    //    [    189    ]
                                            WASTEFLAG,    //    [    190    ]
                                            WASTEFLAG,    //    [    191    ]
                                            WASTEFLAG,    //    [    192    ]
                                            WASTEFLAG,    //    [    193    ]
                                            WASTEFLAG,    //    [    194    ]
                                            WASTEFLAG,    //    [    195    ]
                                            WASTEFLAG,    //    [    196    ]
                                            WASTEFLAG,    //    [    197    ]
                                            WASTEFLAG,    //    [    198    ]
                                            WASTEFLAG,    //    [    199    ]
                                            WASTEFLAG,    //    [    200    ]
                                            WASTEFLAG,    //    [    201    ]
                                            WASTEFLAG,    //    [    202    ]
                                            WASTEFLAG,    //    [    203    ]
                                            WASTEFLAG,    //    [    204    ]
                                            WASTEFLAG,    //    [    205    ]
                                            WASTEFLAG,    //    [    206    ]
                                            WASTEFLAG,    //    [    207    ]
                                            WASTEFLAG,    //    [    208    ]
                                            WASTEFLAG,    //    [    209    ]
                                            WASTEFLAG,    //    [    210    ]
                                            WASTEFLAG,    //    [    211    ]
                                            WASTEFLAG,    //    [    212    ]
                                            WASTEFLAG,    //    [    213    ]
                                            WASTEFLAG,    //    [    214    ]
                                            WASTEFLAG,    //    [    215    ]
                                            WASTEFLAG,    //    [    216    ]
                                            WASTEFLAG,    //    [    217    ]
                                            WASTEFLAG,    //    [    218    ]
                                            WASTEFLAG,    //    [    219    ]
                                            WASTEFLAG,    //    [    220    ]
                                            WASTEFLAG,    //    [    221    ]
                                            WASTEFLAG,    //    [    222    ]
                                            WASTEFLAG,    //    [    223    ]
                                            WASTEFLAG,    //    [    224    ]
                                            WASTEFLAG,    //    [    225    ]
                                            WASTEFLAG,    //    [    226    ]
                                            WASTEFLAG,    //    [    227    ]
                                            WASTEFLAG,    //    [    228    ]
                                            WASTEFLAG,    //    [    229    ]
                                            WASTEFLAG,    //    [    230    ]
                                            WASTEFLAG,    //    [    231    ]
                                            WASTEFLAG,    //    [    232    ]
                                            WASTEFLAG,    //    [    233    ]
                                            WASTEFLAG,    //    [    234    ]
                                            WASTEFLAG,    //    [    235    ]
                                            WASTEFLAG,    //    [    236    ]
                                            WASTEFLAG,    //    [    237    ]
                                            WASTEFLAG,    //    [    238    ]
                                            WASTEFLAG,    //    [    239    ]
                                            WASTEFLAG,    //    [    240    ]
                                            WASTEFLAG,    //    [    241    ]
                                            WASTEFLAG,    //    [    242    ]
                                            WASTEFLAG,    //    [    243    ]
                                            WASTEFLAG,    //    [    244    ]
                                            WASTEFLAG,    //    [    245    ]
                                            WASTEFLAG,    //    [    246    ]
                                            WASTEFLAG,    //    [    247    ]
                                            WASTEFLAG,    //    [    248    ]
                                            WASTEFLAG,    //    [    249    ]
                                            WASTEFLAG,    //    [    250    ]
                                            WASTEFLAG,    //    [    251    ]
                                            WASTEFLAG,    //    [    252    ]
                                            WASTEFLAG,    //    [    253    ]
                                            WASTEFLAG,    //    [    254    ]
                                            WASTEFLAG,    //    [    255    ]
                                            WASTEFLAG,    //    [    256    ]
                                            WASTEFLAG,    //    [    257    ]
                                            WASTEFLAG,    //    [    258    ]
                                            WASTEFLAG,    //    [    259    ]
                                            WASTEFLAG,    //    [    260    ]
                                            WASTEFLAG,    //    [    261    ]
                                            WASTEFLAG,    //    [    262    ]
                                            WASTEFLAG,    //    [    263    ]
                                            WASTEFLAG,    //    [    264    ]
                                            WASTEFLAG,    //    [    265    ]
                                            WASTEFLAG,    //    [    266    ]
                                            WASTEFLAG,    //    [    267    ]
                                            WASTEFLAG,    //    [    268    ]
                                            WASTEFLAG,    //    [    269    ]
                                            WASTEFLAG,    //    [    270    ]
                                            WASTEFLAG,    //    [    271    ]
                                            WASTEFLAG,    //    [    272    ]
                                            WASTEFLAG,    //    [    273    ]
                                            WASTEFLAG,    //    [    274    ]
                                            WASTEFLAG,    //    [    275    ]
                                            WASTEFLAG,    //    [    276    ]
                                            WASTEFLAG,    //    [    277    ]
                                            WASTEFLAG,    //    [    278    ]
                                            WASTEFLAG,    //    [    279    ]
                                            WASTEFLAG,    //    [    280    ]
                                            WASTEFLAG,    //    [    281    ]
                                            WASTEFLAG,    //    [    282    ]
                                            WASTEFLAG,    //    [    283    ]
                                            WASTEFLAG,    //    [    284    ]
                                            WASTEFLAG,    //    [    285    ]
                                            WASTEFLAG,    //    [    286    ]
                                            WASTEFLAG,    //    [    287    ]
                                            WASTEFLAG,    //    [    288    ]
                                            WASTEFLAG,    //    [    289    ]
                                            WASTEFLAG,    //    [    290    ]
                                            WASTEFLAG,    //    [    291    ]
                                            WASTEFLAG,    //    [    292    ]
                                            WASTEFLAG,    //    [    293    ]
                                            WASTEFLAG,    //    [    294    ]
                                            WASTEFLAG,    //    [    295    ]
                                            WASTEFLAG,    //    [    296    ]
                                            WASTEFLAG,    //    [    297    ]
                                            WASTEFLAG,    //    [    298    ]
                                            WASTEFLAG,    //    [    299    ]
                                            WASTEFLAG,    //    [    300    ]
                                            WASTEFLAG,    //    [    301    ]
                                            WASTEFLAG,    //    [    302    ]
                                            WASTEFLAG,    //    [    303    ]
                                            WASTEFLAG,    //    [    304    ]
                                            WASTEFLAG,    //    [    305    ]
                                            WASTEFLAG,    //    [    306    ]
                                            WASTEFLAG,    //    [    307    ]
                                            WASTEFLAG,    //    [    308    ]
                                            WASTEFLAG,    //    [    309    ]
                                            WASTEFLAG,    //    [    310    ]
                                            WASTEFLAG,    //    [    311    ]
                                            WASTEFLAG,    //    [    312    ]
                                            WASTEFLAG,    //    [    313    ]
                                            WASTEFLAG,    //    [    314    ]
                                            WASTEFLAG,    //    [    315    ]
                                            WASTEFLAG,    //    [    316    ]
                                            WASTEFLAG,    //    [    317    ]
                                            WASTEFLAG,    //    [    318    ]
                                            WASTEFLAG,    //    [    319    ]
                                            WASTEFLAG,    //    [    320    ]
                                            WASTEFLAG,    //    [    321    ]
                                            WASTEFLAG,    //    [    322    ]
                                            WASTEFLAG,    //    [    323    ]
                                            WASTEFLAG,    //    [    324    ]
                                            WASTEFLAG,    //    [    325    ]
                                            WASTEFLAG,    //    [    326    ]
                                            WASTEFLAG,    //    [    327    ]
                                            WASTEFLAG,    //    [    328    ]
                                            WASTEFLAG,    //    [    329    ]
                                            WASTEFLAG,    //    [    330    ]
                                            WASTEFLAG,    //    [    331    ]
                                            WASTEFLAG,    //    [    332    ]
                                            WASTEFLAG,    //    [    333    ]
                                            WASTEFLAG,    //    [    334    ]
                                            WASTEFLAG,    //    [    335    ]
                                            WASTEFLAG,    //    [    336    ]
                                            WASTEFLAG,    //    [    337    ]
                                            WASTEFLAG,    //    [    338    ]
                                            WASTEFLAG,    //    [    339    ]
                                            WASTEFLAG,    //    [    340    ]
                                            WASTEFLAG,    //    [    341    ]
                                            WASTEFLAG,    //    [    342    ]
                                            WASTEFLAG,    //    [    343    ]
                                            WASTEFLAG,    //    [    344    ]
                                            WASTEFLAG,    //    [    345    ]
                                            WASTEFLAG,    //    [    346    ]
                                            WASTEFLAG,    //    [    347    ]
                                            WASTEFLAG,    //    [    348    ]
                                            WASTEFLAG,    //    [    349    ]
                                            WASTEFLAG,    //    [    350    ]
                                            WASTEFLAG,    //    [    351    ]
                                            WASTEFLAG,    //    [    352    ]
                                            WASTEFLAG,    //    [    353    ]
                                            WASTEFLAG,    //    [    354    ]
                                            WASTEFLAG,    //    [    355    ]
                                            WASTEFLAG,    //    [    356    ]
                                            WASTEFLAG,    //    [    357    ]
                                            WASTEFLAG,    //    [    358    ]
                                            WASTEFLAG,    //    [    359    ]
                                            WASTEFLAG,    //    [    360    ]
                                            WASTEFLAG,    //    [    361    ]
                                            WASTEFLAG,    //    [    362    ]
                                            WASTEFLAG,    //    [    363    ]
                                            WASTEFLAG,    //    [    364    ]
                                            WASTEFLAG,    //    [    365    ]
                                            WASTEFLAG,    //    [    366    ]
                                            WASTEFLAG,    //    [    367    ]
                                            WASTEFLAG,    //    [    368    ]
                                            WASTEFLAG,    //    [    369    ]
                                            WASTEFLAG,    //    [    370    ]
                                            WASTEFLAG,    //    [    371    ]
                                            WASTEFLAG,    //    [    372    ]
                                            WASTEFLAG,    //    [    373    ]
                                            WASTEFLAG,    //    [    374    ]
                                            WASTEFLAG,    //    [    375    ]
                                            WASTEFLAG,    //    [    376    ]
                                            WASTEFLAG,    //    [    377    ]
                                            WASTEFLAG,    //    [    378    ]
                                            WASTEFLAG,    //    [    379    ]
                                            WASTEFLAG,    //    [    380    ]
                                            WASTEFLAG,    //    [    381    ]
                                            WASTEFLAG,    //    [    382    ]
                                            WASTEFLAG,    //    [    383    ]
                                            WASTEFLAG,    //    [    384    ]
                                            WASTEFLAG,    //    [    385    ]
                                            WASTEFLAG,    //    [    386    ]
                                            WASTEFLAG,    //    [    387    ]
                                            WASTEFLAG,    //    [    388    ]
                                            WASTEFLAG,    //    [    389    ]
                                            WASTEFLAG,    //    [    390    ]
                                            WASTEFLAG,    //    [    391    ]
                                            WASTEFLAG,    //    [    392    ]
                                            WASTEFLAG,    //    [    393    ]
                                            WASTEFLAG,    //    [    394    ]
                                            WASTEFLAG,    //    [    395    ]
                                            WASTEFLAG,    //    [    396    ]
                                            WASTEFLAG,    //    [    397    ]
                                            WASTEFLAG,    //    [    398    ]
                                            WASTEFLAG,    //    [    399    ]
                                            WASTEFLAG,    //    [    400    ]
                                            WASTEFLAG,    //    [    401    ]
                                            WASTEFLAG,    //    [    402    ]
                                            WASTEFLAG,    //    [    403    ]
                                            WASTEFLAG,    //    [    404    ]
                                            WASTEFLAG,    //    [    405    ]
                                            WASTEFLAG,    //    [    406    ]
                                            WASTEFLAG,    //    [    407    ]
                                            WASTEFLAG,    //    [    408    ]
                                            WASTEFLAG,    //    [    409    ]
                                            WASTEFLAG,    //    [    410    ]
                                            WASTEFLAG,    //    [    411    ]
                                            WASTEFLAG,    //    [    412    ]
                                            WASTEFLAG,    //    [    413    ]
                                            WASTEFLAG,    //    [    414    ]
                                            WASTEFLAG,    //    [    415    ]
                                            WASTEFLAG,    //    [    416    ]
                                            WASTEFLAG,    //    [    417    ]
                                            WASTEFLAG,    //    [    418    ]
                                            WASTEFLAG,    //    [    419    ]
                                            WASTEFLAG,    //    [    420    ]
                                            WASTEFLAG,    //    [    421    ]
                                            WASTEFLAG,    //    [    422    ]
                                            WASTEFLAG,    //    [    423    ]
                                            WASTEFLAG,    //    [    424    ]
                                            WASTEFLAG,    //    [    425    ]
                                            WASTEFLAG,    //    [    426    ]
                                            WASTEFLAG,    //    [    427    ]
                                            WASTEFLAG,    //    [    428    ]
                                            WASTEFLAG,    //    [    429    ]
                                            WASTEFLAG,    //    [    430    ]
                                            WASTEFLAG,    //    [    431    ]
                                            WASTEFLAG,    //    [    432    ]
                                            WASTEFLAG,    //    [    433    ]
                                            WASTEFLAG,    //    [    434    ]
                                            WASTEFLAG,    //    [    435    ]
                                            WASTEFLAG,    //    [    436    ]
                                            WASTEFLAG,    //    [    437    ]
                                            WASTEFLAG,    //    [    438    ]
                                            WASTEFLAG,    //    [    439    ]
                                            WASTEFLAG,    //    [    440    ]
                                            WASTEFLAG,    //    [    441    ]
                                            WASTEFLAG,    //    [    442    ]
                                            WASTEFLAG,    //    [    443    ]
                                            WASTEFLAG,    //    [    444    ]
                                            WASTEFLAG,    //    [    445    ]
                                            WASTEFLAG,    //    [    446    ]
                                            WASTEFLAG,    //    [    447    ]
                                            WASTEFLAG,    //    [    448    ]
                                            WASTEFLAG,    //    [    449    ]
                                            WASTEFLAG,    //    [    450    ]
                                            WASTEFLAG,    //    [    451    ]
                                            WASTEFLAG,    //    [    452    ]
                                            WASTEFLAG,    //    [    453    ]
                                            WASTEFLAG,    //    [    454    ]
                                            WASTEFLAG,    //    [    455    ]
                                            WASTEFLAG,    //    [    456    ]
                                            WASTEFLAG,    //    [    457    ]
                                            WASTEFLAG,    //    [    458    ]
                                            WASTEFLAG,    //    [    459    ]
                                            WASTEFLAG,    //    [    460    ]
                                            WASTEFLAG,    //    [    461    ]
                                            WASTEFLAG,    //    [    462    ]
                                            WASTEFLAG,    //    [    463    ]
                                            WASTEFLAG,    //    [    464    ]
                                            WASTEFLAG,    //    [    465    ]
                                            WASTEFLAG,    //    [    466    ]
                                            WASTEFLAG,    //    [    467    ]
                                            WASTEFLAG,    //    [    468    ]
                                            WASTEFLAG,    //    [    469    ]
                                            WASTEFLAG,    //    [    470    ]
                                            WASTEFLAG,    //    [    471    ]
                                            WASTEFLAG,    //    [    472    ]
                                            WASTEFLAG,    //    [    473    ]
                                            WASTEFLAG,    //    [    474    ]
                                            WASTEFLAG,    //    [    475    ]
                                            WASTEFLAG,    //    [    476    ]
                                            WASTEFLAG,    //    [    477    ]
                                            WASTEFLAG,    //    [    478    ]
                                            WASTEFLAG,    //    [    479    ]
                                            WASTEFLAG,    //    [    480    ]
                                            WASTEFLAG,    //    [    481    ]
                                            WASTEFLAG,    //    [    482    ]
                                            WASTEFLAG,    //    [    483    ]
                                            WASTEFLAG,    //    [    484    ]
                                            WASTEFLAG,    //    [    485    ]
                                            WASTEFLAG,    //    [    486    ]
                                            WASTEFLAG,    //    [    487    ]
                                            WASTEFLAG,    //    [    488    ]
                                            WASTEFLAG,    //    [    489    ]
                                            WASTEFLAG,    //    [    490    ]
                                            WASTEFLAG,    //    [    491    ]
                                            WASTEFLAG,    //    [    492    ]
                                            WASTEFLAG,    //    [    493    ]
                                            WASTEFLAG,    //    [    494    ]
                                            WASTEFLAG,    //    [    495    ]
                                            WASTEFLAG,    //    [    496    ]
                                            WASTEFLAG,    //    [    497    ]
                                            WASTEFLAG,    //    [    498    ]
                                            WASTEFLAG,    //    [    499    ]
                                            WASTEFLAG,    //    [    500    ]
                                            WASTEFLAG,    //    [    501    ]
                                            WASTEFLAG,    //    [    502    ]
                                            WASTEFLAG,    //    [    503    ]
                                            WASTEFLAG,    //    [    504    ]
                                            WASTEFLAG,    //    [    505    ]
                                            WASTEFLAG,    //    [    506    ]
                                            WASTEFLAG,    //    [    507    ]
                                            WASTEFLAG,    //    [    508    ]
                                            WASTEFLAG,    //    [    509    ]
                                            WASTEFLAG,    //    [    510    ]
                                            WASTEFLAG,    //    [    511    ]
};

/******************************************************************************/
/* User Global Variable Declaration                                           */
/******************************************************************************/
extern unsigned char FlashBuffer[128];
extern unsigned char Flash_Status;

/******************************************************************************/
/* Macro Functions                                                            */
/******************************************************************************/

/******************************************************************************/
/* Function prototypes                                                        */
/******************************************************************************/
void InitFlash(void);
void FSH_EraseBlock(unsigned long Address);
unsigned char FSH_Write_IR_RF(void);
void FSH_AddressToBlock(unsigned long Address);
void FSH_WriteIntArray(const unsigned int* ConstArray, unsigned int* Array);
unsigned char FSH_VerifyWriteIntArray(const unsigned int* ConstArray, unsigned int* Array);
void FSH_EraseALL(void);

#endif	/* BUTTON_H */